DROP TABLE IF EXISTS confirmations CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS raid_groups CASCADE;
DROP TABLE IF EXISTS characters CASCADE;
DROP TABLE IF EXISTS guilds CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP EXTENSION IF EXISTS "uuid-ossp";